version: '3'
services:
  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082
    networks:
      pix-network:

  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091
    networks:
      pix-network:

  mysql_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: keymanager_db
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      pix-network:

  keymanager-grpc:
    image: "mikkaeru/keymanager-grpc"
    ports:
      - 50051:50051
    environment:
      DB_URI: jdbc:mysql://mysql_db:3306/keymanager_db
      DB_DIALECT: MYSQL
      DB_USER: root
      DB_PASSWORD: admin
      ITAU_URL: http://erp-itau:9091
      BCB_URL: http://bcb:8082
    depends_on:
      - bcb
      - erp-itau
      - mysql_db
    networks:
      pix-network:

volumes:
  mysql-volume:

networks:
  pix-network:
    driver: bridge